release\gen_array_ops_py_wrappers_cc BroadcastGradientArgs,ConcatOffset,Concat,Const,EditDistance,MirrorPad,MirrorPadGrad,OneHot,Pack,Pad,Placeholder,RefIdentity,Split,Slice,TileGrad,ZerosLike,Unpack 1 > tensorflow\python\ops\gen_array_ops.py
release\gen_candidate_sampling_ops_py_wrappers_cc AllCandidateSampler,ComputeAccidentalHits,FixedUnigramCandidateSampler,LearnedUnigramCandidateSampler,LogUniformCandidateSampler,ThreadUnsafeUnigramCandidateSampler,UniformCandidateSampler 1 > tensorflow\python\ops\gen_candidate_sampling_ops.py
release\gen_control_flow_ops_py_wrappers_cc Switch,Merge,RefMerge,Exit,RefExit 1 > tensorflow\python\ops\gen_control_flow_ops.py
release\gen_ctc_ops_py_wrappers_cc CTCLoss,CTCGreedyDecoder,CTCBeamSearchDecoder 1 > tensorflow\python\ops\gen_ctc_ops.py
release\gen_data_flow_ops_py_wrappers_cc FIFOQueue,HashTable,InitializeTable,LookupTableFind,LookupTableSize,Mutex,MutexAcquire,MutexRelease,PaddingFIFOQueue,QueueClose,QueueDequeue,QueueDequeueMany,QueueDequeueUpTo,QueueEnqueue,QueueEnqueueMany,QueueSize,RandomShuffleQueue,Stack,StackPop,StackPush,StackClose,TensorArray,TensorArrayClose,TensorArrayConcat,TensorArrayGrad,TensorArrayRead,TensorArrayPack,TensorArraySize,TensorArraySplit,TensorArrayUnpack,TensorArrayWrite,GetSessionHandle,GetSessionTensor,DeleteSessionTensor 1 > tensorflow\python\ops\gen_data_flow_ops.py
release\gen_functional_ops_py_wrappers_cc SymbolicGradient 0 > tensorflow\python\ops\gen_functional_ops.py
release\gen_image_ops_py_wrappers_cc RandomCrop,ResizeBilinearGrad,ResizeNearestNeighborGrad,AdjustContrastv2,ScaleImageGrad 1 > tensorflow\python\ops\gen_image_ops.py
release\gen_io_ops_py_wrappers_cc FixedLengthRecordReader,IdentityReader,ReaderClose,ReaderEnqueueWork,ReaderNumRecordsProduced,ReaderNumWorkUnitsCompleted,ReaderRead,ReaderReset,ReaderRestoreState,ReaderSerializeState,ReaderWorkQueueLength,Restore,RestoreSlice,Save,SaveSlices,ShardedFilename,ShardedFilespec,TextLineReader,TFRecordReader,WholeFileReader 1 > tensorflow\python\ops\gen_io_ops.py
release\gen_linalg_ops_py_wrappers_cc 1 > tensorflow\python\ops\gen_linalg_ops.py
release\gen_logging_ops_py_wrappers_cc Assert,AudioSummary,HistogramAccumulatorSummary,HistogramSummary,ImageSummary,MergeSummary,Print,ScalarSummary 1 > tensorflow\python\ops\gen_logging_ops.py
release\gen_math_ops_py_wrappers_cc Abs,All,Any,BatchMatMul,Complex,Max,Mean,Min,Pow,Prod,Range,SparseMatMul,Sum,MatMul,Sigmoid,Tanh 1 > tensorflow\python\ops\gen_math_ops.py
release\gen_nn_ops_py_wrappers_cc AvgPoolGrad,BatchNormWithGlobalNormalization,BatchNormWithGlobalNormalizationGrad,SoftmaxCrossEntropyWithLogits,SparseSoftmaxCrossEntropyWithLogits,LRNGrad,MaxPoolGrad,MaxPoolGradWithArgmax,ReluGrad,Relu6Grad,EluGrad,SoftplusGrad,SoftsignGrad,TopK,TopKV2,BiasAdd,BiasAddV1,Relu6,AvgPool,MaxPool 1 > tensorflow\python\ops\gen_nn_ops.py
release\gen_parsing_ops_py_wrappers_cc ParseExample,ParseSingleSequenceExample 1 > tensorflow\python\ops\gen_parsing_ops.py
release\gen_random_ops_py_wrappers_cc RandomUniform,RandomUniformInt,RandomShuffle,RandomStandardNormal,TruncatedNormal 1 > tensorflow\python\ops\gen_random_ops.py
release\gen_script_ops_py_wrappers_cc 1 > tensorflow\python\ops\gen_script_ops.py
release\gen_sparse_ops_py_wrappers_cc DeserializeManySparse,SerializeManySparse,SerializeSparse,SparseAdd,SparseAddGrad,SparseConcat,SparseSplit,SparseSelectLastK,SparseReorder,SparseToDense,SparseTensorDenseAdd,SparseTensorDenseMatMul 1 > tensorflow\python\ops\gen_sparse_ops.py
release\gen_state_ops_py_wrappers_cc Variable,TemporaryVariable,DestroyTemporaryVariable 1 > tensorflow\python\ops\gen_state_ops.py
release\gen_string_ops_py_wrappers_cc 1 > tensorflow\python\ops\gen_string_ops.py
release\gen_training_ops_py_wrappers_cc 1 > tensorflow\python\training\gen_training_ops.py
release\gen_user_ops_py_wrappers_cc Fact 0 > tensorflow\python\ops\gen_user_ops.py
release\gen_sdca_ops_py_wrappers_cc 0 > tensorflow/contrib/linear_optimizer/ops/gen_sdca_ops.py
release\gen_quantization_array_ops_py_wrappers_cc 0 > tensorflow\contrib\quantization\ops\gen_array_ops.py
release\gen_quantization_math_ops_py_wrappers_cc 0 > tensorflow\contrib\quantization\ops\gen_math_ops.py
release\gen_quantization_nn_ops_py_wrappers_cc 0 > tensorflow\contrib\quantization\ops\gen_nn_ops.py
release\gen_word2vec_ops_py_wrappers_cc 0 > tensorflow\models\embedding\gen_word2vec.py