cd %~dp0
release\gen_cc_op_array_ops tensorflow/cc/ops/array_ops.h tensorflow/cc/ops/array_ops.cc 0
release\gen_cc_op_candidate_sampling_ops tensorflow/cc/ops/candidate_sampling_ops.h tensorflow/cc/ops/candidate_sampling_ops.cc 0
release\gen_cc_op_control_flow_ops tensorflow/cc/ops/control_flow_ops.h tensorflow/cc/ops/control_flow_ops.cc 0
release\gen_cc_op_data_flow_ops tensorflow/cc/ops/data_flow_ops.h tensorflow/cc/ops/data_flow_ops.cc 0
release\gen_cc_op_image_ops tensorflow/cc/ops/image_ops.h tensorflow/cc/ops/image_ops.cc 0
release\gen_cc_op_io_ops tensorflow/cc/ops/io_ops.h tensorflow/cc/ops/io_ops.cc 0
release\gen_cc_op_linalg_ops tensorflow/cc/ops/linalg_ops.h tensorflow/cc/ops/linalg_ops.cc 0
release\gen_cc_op_logging_ops tensorflow/cc/ops/logging_ops.h tensorflow/cc/ops/logging_ops.cc 0
release\gen_cc_op_math_ops tensorflow/cc/ops/math_ops.h tensorflow/cc/ops/math_ops.cc 0
release\gen_cc_op_nn_ops tensorflow/cc/ops/nn_ops.h tensorflow/cc/ops/nn_ops.cc 0
release\gen_cc_op_no_op tensorflow/cc/ops/no_op.h tensorflow/cc/ops/no_op.cc 0
release\gen_cc_op_parsing_ops tensorflow/cc/ops/parsing_ops.h tensorflow/cc/ops/parsing_ops.cc 0
release\gen_cc_op_random_ops tensorflow/cc/ops/random_ops.h tensorflow/cc/ops/random_ops.cc 0
release\gen_cc_op_sendrecv_ops tensorflow/cc/ops/sendrecv_ops.h tensorflow/cc/ops/sendrecv_ops.cc 1
release\gen_cc_op_sparse_ops tensorflow/cc/ops/sparse_ops.h tensorflow/cc/ops/sparse_ops.cc 0
release\gen_cc_op_state_ops tensorflow/cc/ops/state_ops.h tensorflow/cc/ops/state_ops.cc 0
release\gen_cc_op_string_ops tensorflow/cc/ops/string_ops.h tensorflow/cc/ops/string_ops.cc 0
release\gen_cc_op_training_ops tensorflow/cc/ops/training_ops.h tensorflow/cc/ops/training_ops.cc 0
release\gen_cc_op_user_ops tensorflow/cc/ops/user_ops.h tensorflow/cc/ops/user_ops.cc 0