// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/master_service.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "tensorflow/core/protobuf/master_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tensorflow {
namespace grpc {

namespace {


}  // namespace


void protobuf_AssignDesc_tensorflow_2fcore_2fprotobuf_2fmaster_5fservice_2eproto() {
  protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fmaster_5fservice_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "tensorflow/core/protobuf/master_service.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_tensorflow_2fcore_2fprotobuf_2fmaster_5fservice_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_tensorflow_2fcore_2fprotobuf_2fmaster_5fservice_2eproto() {
}

void protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fmaster_5fservice_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::tensorflow::protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fmaster_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n-tensorflow/core/protobuf/master_servic"
    "e.proto\022\017tensorflow.grpc\032%tensorflow/cor"
    "e/protobuf/master.proto2\340\003\n\rMasterServic"
    "e\022T\n\rCreateSession\022 .tensorflow.CreateSe"
    "ssionRequest\032!.tensorflow.CreateSessionR"
    "esponse\022T\n\rExtendSession\022 .tensorflow.Ex"
    "tendSessionRequest\032!.tensorflow.ExtendSe"
    "ssionResponse\022B\n\007RunStep\022\032.tensorflow.Ru"
    "nStepRequest\032\033.tensorflow.RunStepRespons"
    "e\022Q\n\014CloseSession\022\037.tensorflow.CloseSess"
    "ionRequest\032 .tensorflow.CloseSessionResp"
    "onse\022N\n\013ListDevices\022\036.tensorflow.ListDev"
    "icesRequest\032\037.tensorflow.ListDevicesResp"
    "onse\022<\n\005Reset\022\030.tensorflow.ResetRequest\032"
    "\031.tensorflow.ResetResponseB3\n\032org.tensor"
    "flow.distruntimeB\023MasterServiceProtosP\001b"
    "\006proto3", 647);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tensorflow/core/protobuf/master_service.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_tensorflow_2fcore_2fprotobuf_2fmaster_5fservice_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_tensorflow_2fcore_2fprotobuf_2fmaster_5fservice_2eproto {
  StaticDescriptorInitializer_tensorflow_2fcore_2fprotobuf_2fmaster_5fservice_2eproto() {
    protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fmaster_5fservice_2eproto();
  }
} static_descriptor_initializer_tensorflow_2fcore_2fprotobuf_2fmaster_5fservice_2eproto_;

// @@protoc_insertion_point(namespace_scope)

}  // namespace grpc
}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)
