// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/worker_service.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "tensorflow/core/protobuf/worker_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tensorflow {
namespace grpc {

namespace {


}  // namespace


void protobuf_AssignDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto() {
  protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "tensorflow/core/protobuf/worker_service.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto() {
}

void protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::tensorflow::protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n-tensorflow/core/protobuf/worker_servic"
    "e.proto\022\017tensorflow.grpc\032%tensorflow/cor"
    "e/protobuf/worker.proto2\311\005\n\rWorkerServic"
    "e\022H\n\tGetStatus\022\034.tensorflow.GetStatusReq"
    "uest\032\035.tensorflow.GetStatusResponse\022T\n\rR"
    "egisterGraph\022 .tensorflow.RegisterGraphR"
    "equest\032!.tensorflow.RegisterGraphRespons"
    "e\022Z\n\017DeregisterGraph\022\".tensorflow.Deregi"
    "sterGraphRequest\032#.tensorflow.Deregister"
    "GraphResponse\022E\n\010RunGraph\022\033.tensorflow.R"
    "unGraphRequest\032\034.tensorflow.RunGraphResp"
    "onse\022Q\n\014CleanupGraph\022\037.tensorflow.Cleanu"
    "pGraphRequest\032 .tensorflow.CleanupGraphR"
    "esponse\022K\n\nCleanupAll\022\035.tensorflow.Clean"
    "upAllRequest\032\036.tensorflow.CleanupAllResp"
    "onse\022M\n\nRecvTensor\022\035.tensorflow.RecvTens"
    "orRequest\032\036.tensorflow.RecvTensorRespons"
    "e\"\000\022B\n\007Logging\022\032.tensorflow.LoggingReque"
    "st\032\033.tensorflow.LoggingResponse\022B\n\007Traci"
    "ng\022\032.tensorflow.TracingRequest\032\033.tensorf"
    "low.TracingResponseB3\n\032org.tensorflow.di"
    "struntimeB\023WorkerServiceProtosP\001b\006proto3", 880);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tensorflow/core/protobuf/worker_service.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto {
  StaticDescriptorInitializer_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto() {
    protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto();
  }
} static_descriptor_initializer_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_;

// @@protoc_insertion_point(namespace_scope)

}  // namespace grpc
}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)
